// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OnlineAuction.Data;

namespace OnlineAuction.Migrations;

[DbContext(typeof(AuctionHouseDbContext))]
[Migration("20260617060000_BackfillBuyNowListingType")]
partial class BackfillBuyNowListingType
{
}
