static class Bilingual
{
    public static string Bi(string en, string vi) => $"{en}\n{vi}";
}

record BilingualCase(
    int No,
    string Type,
    string ItemEn,
    string ItemVi,
    string ConditionEn,
    string ConditionVi,
    string ExpectedEn,
    string ExpectedVi);

static class TestCasesData
{
    static BilingualCase C(int no, string type,
        string ie, string iv, string ce, string cv, string ee, string ev)
        => new(no, type, ie, iv, ce, cv, ee, ev);

    public static BilingualCase[] All =>
    [
        C(1, "SETUP-01", "Database & migrations", "Cơ sở dữ liệu & migration",
            "MySQL running; dotnet ef database update", "MySQL đang chạy; dotnet ef database update",
            "Schema applied; seeders run without error", "Schema áp dụng; seeder chạy không lỗi"),
        C(2, "SETUP-02", "App startup", "Khởi động ứng dụng",
            "dotnet run --launch-profile http", "dotnet run --launch-profile http",
            "App on http://localhost:5006; catalog seeded in Development", "App tại http://localhost:5006; catalog được seed ở Development"),
        C(3, "SETUP-03", "Test accounts", "Tài khoản test",
            "UserSeeder applied", "UserSeeder đã chạy",
            "user1@auctionhouse.local / User@123; admin@auctionhouse.com for Admin login", "user1@auctionhouse.local / User@123; admin@auctionhouse.com cho Admin login"),

        C(4, "AUTH-01", "Sign up valid", "Đăng ký hợp lệ",
            "POST /Auth/SignUp with unique email, password policy met", "POST /Auth/SignUp email mới, đúng chính sách mật khẩu",
            "User created; redirect/login; User cookie set", "Tạo user; redirect/login; cookie User được set"),
        C(5, "AUTH-02", "Sign up duplicate email", "Đăng ký email trùng",
            "Sign up with existing email", "Đăng ký email đã tồn tại",
            "Validation error; no duplicate user", "Lỗi validation; không tạo user trùng"),
        C(6, "AUTH-03", "Login valid user", "Đăng nhập user hợp lệ",
            "POST /Auth/Login user1@auctionhouse.local / User@123", "POST /Auth/Login user1@auctionhouse.local / User@123",
            "User cookie; header shows logged-in state", "Cookie User; header hiển thị đã đăng nhập"),
        C(7, "AUTH-04", "Login inactive user", "Đăng nhập user bị khóa",
            "Login user4@auctionhouse.local (inactive)", "Login user4@auctionhouse.local (inactive)",
            "Rejected with appropriate message", "Bị từ chối với thông báo phù hợp"),
        C(8, "AUTH-05", "Admin on public login", "Admin đăng nhập trang public",
            "Admin account on /Auth/Login", "Tài khoản Admin tại /Auth/Login",
            "Rejected — use admin login page", "Bị từ chối — dùng trang admin login"),
        C(9, "AUTH-06", "Logout public", "Đăng xuất public",
            "POST /Auth/Logout while logged in", "POST /Auth/Logout khi đã login",
            "User cookie cleared; guest header", "Xóa cookie User; header hiển thị guest"),
        C(10, "AUTH-07", "Protected page redirect", "Redirect trang bảo vệ",
            "Open /Order without login", "Mở /Order chưa đăng nhập",
            "Redirect to /Auth/Login?returnUrl=…", "Redirect tới /Auth/Login?returnUrl=…"),
        C(11, "AUTH-08", "Password policy", "Chính sách mật khẩu",
            "Sign up password < 6 chars or missing upper/lower/digit", "Mật khẩu < 6 ký tự hoặc thiếu hoa/thường/số",
            "Validation errors shown", "Hiển thị lỗi validation"),

        C(12, "ADM-AUTH-01", "Admin login", "Đăng nhập Admin",
            "/Admin/Account/Login admin@auctionhouse.com", "/Admin/Account/Login admin@auctionhouse.com",
            "Admin cookie (path /Admin); dashboard accessible", "Cookie Admin (path /Admin); truy cập dashboard"),
        C(13, "ADM-AUTH-02", "Dual session isolation", "Tách session kép",
            "Login Admin → open /", "Login Admin → mở /",
            "Public header shows Guest (Admin cookie not sent)", "Header public hiển thị Guest (cookie Admin không gửi)"),
        C(14, "ADM-AUTH-03", "User cannot access Admin", "User không vào Admin",
            "Login User → /Admin/Dashboard", "Login User → /Admin/Dashboard",
            "Redirect to Admin login", "Redirect tới Admin login"),
        C(15, "ADM-AUTH-04", "Both sessions parallel", "Hai session song song",
            "Login Admin + User without logout", "Login Admin + User không logout",
            "Each area uses correct identity", "Mỗi khu vực dùng đúng identity"),
        C(16, "ADM-AUTH-05", "Independent logout", "Logout độc lập",
            "Logout Admin only", "Chỉ logout Admin",
            "User session remains active", "Session User vẫn active"),

        C(17, "AUTH-REG-01", "Sign up + confirm", "Đăng ký + xác nhận",
            "SmokeTesting enabled; Invoke-ReleaseSmoke.ps1", "Bật SmokeTesting; chạy Invoke-ReleaseSmoke.ps1",
            "New user registered (or smoke helper confirms)", "User mới đăng ký (hoặc smoke helper xác nhận)"),
        C(18, "AUTH-LOGIN-01", "Smoke login", "Smoke login",
            "Smoke script login step", "Bước login của smoke script",
            "Cookie session established", "Session cookie được thiết lập"),
        C(19, "AUCTION_REG-03", "Register + deposit", "Đăng ký + đặt cọc",
            "Register for live auction; deposit flow (smoke complete)", "Đăng ký auction live; flow đặt cọc (smoke complete)",
            "Registration pending/approved; deposit recorded or smoke bypass", "Đăng ký pending/approved; deposit ghi nhận hoặc smoke bypass"),
        C(20, "BID-01", "Place bid (smoke)", "Đặt giá (smoke)",
            "Bid minNextBid on registered auction", "Bid minNextBid trên auction đã đăng ký",
            "Bid accepted; price updated", "Bid được chấp nhận; giá cập nhật"),

        C(21, "CAT-01", "Home auction section", "Mục auction trang chủ",
            "Open /", "Mở /",
            "Shows live/scheduled-in-window auctions only", "Chỉ hiển thị auction live/scheduled trong cửa sổ"),
        C(22, "CAT-02", "Auction index", "Danh sách auction",
            "Open /Auction", "Mở /Auction",
            "Live + eligible scheduled listings; no confirming/rejected", "Live + scheduled hợp lệ; không có confirming/rejected"),
        C(23, "CAT-03", "Buy Now excluded from /Auction", "Buy Now không ở /Auction",
            "Listing type buynow only", "Listing chỉ loại buynow",
            "Not shown on /Auction index", "Không hiển thị trên /Auction"),
        C(24, "CAT-04", "Scheduled before reg window", "Scheduled trước cửa sổ đăng ký",
            "Approved scheduled before RegistrationStartDate", "Scheduled đã duyệt trước RegistrationStartDate",
            "Hidden from public catalog", "Ẩn khỏi catalog public"),
        C(25, "CAT-05", "Confirming hidden", "Confirming bị ẩn",
            "Seller listing in confirming", "Listing seller ở confirming",
            "Not on Home or /Auction", "Không ở Home hoặc /Auction"),
        C(26, "CAT-06", "Buy Now catalog", "Catalog Buy Now",
            "Open /BuyNow", "Mở /BuyNow",
            "Listings with buy_now_price shown", "Hiển thị listing có buy_now_price"),
        C(27, "CAT-07", "Detail URL uses auction id", "URL detail dùng auction id",
            "Open /Auction/Detail/{auctionId}", "Mở /Auction/Detail/{auctionId}",
            "Product detail loads for valid public auction", "Detail sản phẩm load cho auction public hợp lệ"),
        C(28, "CAT-08", "Search/filter (if enabled)", "Tìm kiếm/lọc (nếu có)",
            "Use catalog filters", "Dùng bộ lọc catalog",
            "Results match filter criteria", "Kết quả khớp tiêu chí lọc"),

        C(29, "BID-02", "Valid bid", "Bid hợp lệ",
            "Registered bidder; amount >= minNextBid; valid increment", "Bidder đã đăng ký; amount >= minNextBid; bước giá hợp lệ",
            "Bid saved; current price updated; history entry", "Lưu bid; cập nhật giá; có lịch sử bid"),
        C(30, "BID-03", "Below minimum", "Dưới mức tối thiểu",
            "Bid below minNextBid", "Bid dưới minNextBid",
            "Rejected; price unchanged", "Từ chối; giá không đổi"),
        C(31, "BID-04", "Invalid increment", "Bước giá không hợp lệ",
            "Bid not multiple of bid step", "Bid không phải bội số bid step",
            "Rejected with increment message", "Từ chối kèm thông báo bước giá"),
        C(32, "BID-05", "Unregistered bidder", "Bidder chưa đăng ký",
            "User not registered for auction", "User chưa đăng ký auction",
            "Blocked — must register first", "Bị chặn — phải đăng ký trước"),
        C(33, "BID-06", "Seller self-bid", "Seller tự bid",
            "Seller bids own auction", "Seller bid auction của mình",
            "Rejected", "Từ chối"),
        C(34, "BID-07", "Before start / after end", "Trước start / sau end",
            "Bid outside live window", "Bid ngoài cửa sổ live",
            "Rejected with schedule message", "Từ chối kèm thông báo lịch"),
        C(35, "BID-08", "Disallowed status", "Trạng thái không cho bid",
            "Bid on confirming/cancelled/ended auction", "Bid trên confirming/cancelled/ended",
            "Rejected", "Từ chối"),
        C(36, "BID-09", "Two buyers compete", "Hai buyer cạnh tranh",
            "Buyer A then Buyer B higher bid", "Buyer A rồi Buyer B bid cao hơn",
            "B wins; winning bid updated", "B thắng; winning bid cập nhật"),
        C(37, "BID-10", "Same buyer raises", "Cùng buyer tăng giá",
            "Same user raises own winning bid", "User tăng bid thắng của chính mình",
            "Allowed; winning bid updated", "Cho phép; winning bid cập nhật"),
        C(38, "BID-11", "CanBid UI flag", "Cờ CanBid trên UI",
            "Guest / unregistered / seller on detail page", "Guest / chưa đăng ký / seller trên detail",
            "CanBid=false with correct reason", "CanBid=false với lý do đúng"),
        C(39, "BID-12", "Anti-snipe extension", "Gia hạn anti-snipe",
            "Bid in last N minutes before end", "Bid trong N phút cuối trước khi kết thúc",
            "EndDate extended per config", "EndDate được gia hạn theo config"),

        C(40, "AUCTION_REG-01", "Registration form", "Form đăng ký",
            "Logged-in user on live auction Register", "User đã login bấm Register trên auction live",
            "Registration record created pending deposit", "Tạo bản ghi đăng ký chờ đặt cọc"),
        C(41, "AUCTION_REG-02", "Deposit calculation", "Tính tiền đặt cọc",
            "Register on auction with starting price", "Đăng ký auction có starting price",
            "Deposit = max(minimum, percent of value)", "Deposit = max(tối thiểu, % giá trị)"),
        C(42, "AUCTION_REG-04", "PayPal deposit happy path", "PayPal đặt cọc thành công",
            "Complete PayPal sandbox deposit capture", "Hoàn tất capture deposit PayPal sandbox",
            "Deposit status paid; registration approved", "Deposit paid; đăng ký approved"),
        C(43, "AUCTION_REG-05", "Deposit cancel", "Hủy đặt cọc",
            "Cancel PayPal on deposit", "Hủy PayPal khi đặt cọc",
            "Deposit remains pending; user can retry", "Deposit vẫn pending; user thử lại được"),
        C(44, "AUCTION_REG-06", "Confirming blocks registration", "Confirming chặn đăng ký",
            "Try register on confirming listing", "Thử đăng ký listing confirming",
            "Blocked with confirming message", "Bị chặn kèm thông báo confirming"),
        C(45, "AUCTION_REG-07", "Approved registration enables bid", "Đăng ký approved cho phép bid",
            "After paid deposit", "Sau khi trả deposit",
            "PlaceBid succeeds", "PlaceBid thành công"),

        C(46, "BN-01", "Buy Now detail", "Chi tiết Buy Now",
            "Open /BuyNow/Detail/{id}", "Mở /BuyNow/Detail/{id}",
            "Price, images, specs, documents tab if any", "Giá, ảnh, specs, tab documents nếu có"),
        C(47, "BN-02", "Instant purchase", "Mua ngay",
            "Click Buy Now while logged in", "Bấm Buy Now khi đã login",
            "Order created source=buy_now; pending_payment", "Tạo order source=buy_now; pending_payment"),
        C(48, "BN-03", "Guest purchase", "Mua khi chưa login",
            "Buy Now without login", "Buy Now chưa đăng nhập",
            "Redirect to login or prompt auth", "Redirect login hoặc yêu cầu auth"),
        C(49, "BN-04", "Confirming not listed", "Confirming không lên catalog",
            "Buy Now on confirming product", "Buy Now trên sản phẩm confirming",
            "404 or not in catalog", "404 hoặc không có trong catalog"),
        C(50, "BN-05", "Add to cart / multi select", "Chọn nhiều invoice Buy Now",
            "Select multiple buy-now invoices at /Order", "Chọn nhiều invoice buy_now tại /Order",
            "Checkout totals reflect selected only", "Tổng checkout chỉ invoice được chọn"),
        C(51, "BN-06", "Expired buy-now order", "Order Buy Now hết hạn",
            "Do not pay within 7 days", "Không thanh toán trong 7 ngày",
            "Order cancelled; listing back live if end_date future", "Order cancelled; listing live lại nếu end_date còn tương lai"),

        C(52, "SELL-01", "Create auction listing", "Tạo listing auction",
            "/Sell/Create full form + gallery + docs", "/Sell/Create đầy đủ form + gallery + docs",
            "Listing status confirming; seller notified awaiting admin", "Status confirming; seller được thông báo chờ admin"),
        C(53, "SELL-02", "Create Buy Now listing", "Tạo listing Buy Now",
            "/Sell/BuyNow", "/Sell/BuyNow",
            "confirming buynow listing; no reg schedule required", "Listing buynow confirming; không cần lịch đăng ký"),
        C(54, "SELL-03", "Client validation", "Validation phía client",
            "Submit empty required fields", "Submit thiếu trường bắt buộc",
            "JS + server errors (Sell_Error_*)", "Lỗi JS + server (Sell_Error_*)"),
        C(55, "SELL-04", "Schedule validation", "Validation lịch",
            "Reg end after live start etc.", "Reg end sau live start v.v.",
            "AuctionScheduleHelper messages", "Thông báo AuctionScheduleHelper"),
        C(56, "SELL-05", "Gallery max 5", "Gallery tối đa 5",
            "Upload >5 images", "Upload >5 ảnh",
            "Validation error", "Lỗi validation"),
        C(57, "SELL-06", "Document PDF rules", "Quy tắc PDF",
            "Non-PDF or >5MB or >5 docs", "Không phải PDF hoặc >5MB hoặc >5 file",
            "Validation errors", "Lỗi validation"),
        C(58, "SELL-07", "Edit rejected listing", "Sửa listing bị reject",
            "Seller edits after reject → resubmit", "Seller sửa sau reject → gửi lại",
            "Status back to confirming", "Status về confirming"),
        C(59, "SELL-08", "Seller submissions page", "Trang submissions seller",
            "Account → Selling / Submissions", "Account → Selling / Submissions",
            "Badges: Confirming / Rejected with reason", "Badge: Confirming / Rejected kèm lý do"),

        C(60, "ADM-SYNC-01", "Admin Create Auction", "Admin tạo Auction",
            "Admin → Create Auction → full fields → Save", "Admin → Create Auction → đủ field → Save",
            "DB: specs, gallery, docs; listing_type=auction; RequiresRegistration=true", "DB: specs, gallery, docs; listing_type=auction; RequiresRegistration=true"),
        C(61, "ADM-SYNC-02", "Admin Create Buy Now", "Admin tạo Buy Now",
            "Admin → Create Buy Now", "Admin → Create Buy Now",
            "listing_type=buynow; synthetic schedule; no reg UI", "listing_type=buynow; lịch synthetic; không UI đăng ký"),
        C(62, "ADM-SYNC-03", "Public card parity", "Card public đồng bộ",
            "Set listing live; view public card/detail", "Set listing live; xem card/detail public",
            "Grade, year, subtitle match Sell mapping", "Grade, year, subtitle khớp mapping Sell"),
        C(63, "ADM-SYNC-04", "Preview Auction live", "Preview Auction realtime",
            "Change name/price/image/schedule on form", "Đổi tên/giá/ảnh/lịch trên form",
            "Preview card updates immediately", "Preview card cập nhật ngay"),
        C(64, "ADM-SYNC-05", "Preview Buy Now live", "Preview Buy Now realtime",
            "Change price/image on Buy Now form", "Đổi giá/ảnh trên form Buy Now",
            "Buy Now preview updates", "Preview Buy Now cập nhật"),
        C(65, "ADM-SYNC-06", "Admin schedule validation", "Validation lịch Admin",
            "Invalid schedule on admin auction form", "Lịch không hợp lệ trên form admin auction",
            "Same errors as Sell", "Lỗi giống Sell"),
        C(66, "ADM-SYNC-07", "Admin edit missing specs", "Admin sửa thiếu specs",
            "Edit old listing; add year/grade", "Sửa listing cũ; thêm year/grade",
            "Persisted; existing gallery retained", "Lưu được; gallery cũ giữ nguyên"),
        C(67, "ADM-SYNC-08", "Admin upload PDF doc", "Admin upload PDF",
            "Dropzone + cert name → Save", "Dropzone + tên cert → Save",
            "product_documents row; visible on Admin Details", "Có product_documents; hiện trên Admin Details"),

        C(68, "VERIFY-01", "Confirming queue", "Hàng đợi confirming",
            "/Admin/AuctionVerification", "/Admin/AuctionVerification",
            "Lists confirming seller submissions; badge count", "Liệt kê submission confirming; badge đếm"),
        C(69, "VERIFY-02", "Review details", "Xem chi tiết duyệt",
            "Open Details/{id}", "Mở Details/{id}",
            "Product, grading, media, schedule visible", "Hiển thị product, grading, media, lịch"),
        C(70, "VERIFY-03", "Approve valid listing", "Duyệt listing hợp lệ",
            "Approve with valid image + description + prices", "Approve với ảnh + mô tả + giá hợp lệ",
            "Status scheduled or live; seller notified; verified_at set", "Status scheduled/live; thông báo seller; verified_at set"),
        C(71, "VERIFY-04", "Reject with reason", "Từ chối kèm lý do",
            "Reject; reason min 10 chars", "Reject; lý do tối thiểu 10 ký tự",
            "status=rejected; reject_reason stored; seller notified", "status=rejected; lưu reject_reason; thông báo seller"),
        C(72, "VERIFY-05", "Approve validation fail", "Approve bị chặn validation",
            "Missing image or invalid prices", "Thiếu ảnh hoặc giá không hợp lệ",
            "Approve blocked with validation", "Approve bị chặn bởi validation"),
        C(73, "VERIFY-06", "Admin direct create bypass", "Admin tạo trực tiếp bỏ queue",
            "Admin Create with status live", "Admin Create status live",
            "Skips queue; public immediately if live", "Bỏ queue; public ngay nếu live"),
        C(74, "VERIFY-07", "Owner preview confirming", "Owner xem confirming",
            "Seller opens own confirming detail URL", "Seller mở URL detail confirming của mình",
            "Allowed for owner; 404 for guest", "Owner được; guest 404"),
        C(75, "VERIFY-08", "Gates while confirming", "Chặn khi confirming",
            "Bid / register / watchlist on confirming", "Bid / đăng ký / watchlist trên confirming",
            "All blocked for non-owner", "Tất cả bị chặn với non-owner"),

        C(76, "DASH-01", "Default date filter", "Bộ lọc ngày mặc định",
            "Open /Admin/Dashboard", "Mở /Admin/Dashboard",
            "Last 30 UTC days; period KPIs filtered", "30 ngày UTC gần nhất; KPI theo kỳ được lọc"),
        C(77, "DASH-02", "GMV & fees", "GMV & phí",
            "Orders paid in period", "Order paid trong kỳ",
            "GMV, commission, buyer/seller fees match AdminDashboardService", "GMV, commission, phí buyer/seller khớp AdminDashboardService"),
        C(78, "DASH-03", "Snapshot metrics", "Metric snapshot",
            "Ongoing / Ended / Pending verification", "Ongoing / Ended / Pending verification",
            "As-of-now counts; not date-filtered", "Đếm tại thời điểm hiện tại; không lọc theo ngày"),
        C(79, "DASH-04", "Export Excel", "Xuất Excel",
            "Click Export", "Bấm Export",
            "Same numbers as UI for selected range", "Số liệu giống UI cho khoảng đã chọn"),
        C(80, "DASH-05", "Invalid date range", "Khoảng ngày không hợp lệ",
            "DateFrom > DateTo or range > 365 days", "DateFrom > DateTo hoặc >365 ngày",
            "Validation error", "Lỗi validation"),
        C(81, "DASH-06", "Pending verification widget", "Widget pending verification",
            "Dashboard widget link", "Link widget dashboard",
            "Navigates to verification queue", "Đi tới hàng đợi verification"),

        C(82, "ADM-CRUD-01", "Category CRUD", "CRUD danh mục",
            "Admin Categories create/edit/delete", "Admin Categories tạo/sửa/xóa",
            "Category persisted; used in listings", "Category lưu; dùng trong listing"),
        C(83, "ADM-CRUD-02", "User management", "Quản lý user",
            "Admin Users list/edit active flag", "Admin Users sửa cờ active",
            "User status updated; inactive cannot login", "Cập nhật status; inactive không login"),
        C(84, "ADM-CRUD-03", "Product admin edit", "Admin sửa product",
            "Admin Products edit", "Admin Products edit",
            "Fields saved; documents soft-delete works", "Lưu field; soft-delete documents hoạt động"),
        C(85, "ADM-CRUD-04", "Permission policy", "Chính sách permission",
            "Admin without permission hits protected action", "Admin thiếu permission truy cập action",
            "403 / forbidden", "403 / forbidden"),
        C(86, "ADM-CRUD-05", "Superuser bypass", "Superuser bypass",
            "Role Admin accesses all modules", "Role Admin truy cập mọi module",
            "All admin routes allowed", "Mọi route admin được phép"),
        C(87, "ADM-CRUD-06", "Complaints module", "Module khiếu nại",
            "/Admin/Complaint", "/Admin/Complaint",
            "List/review complaints if data exists", "Liệt kê/xem khiếu nại nếu có dữ liệu"),
        C(88, "ADM-CRUD-07", "Auction admin list", "Danh sách auction admin",
            "/Admin/Auction", "/Admin/Auction",
            "Filter/search auctions; edit/delete actions", "Lọc/tìm auction; sửa/xóa"),
        C(89, "ADM-CRUD-08", "Buy Now admin", "Admin Buy Now",
            "/Admin/BuyNow", "/Admin/BuyNow",
            "Manage buy-now listings", "Quản lý listing buy-now"),

        C(90, "ORD-01", "List pending invoices", "Danh sách invoice chờ",
            "Winner/buyer opens /Order", "Winner/buyer mở /Order",
            "All pending_payment orders for user shown", "Hiển thị mọi order pending_payment của user"),
        C(91, "ORD-02", "Auction win mandatory", "Auction win bắt buộc",
            "Checkout with auction_win + buy_now", "Checkout có auction_win + buy_now",
            "Auction win checkbox disabled checked", "Checkbox auction win disabled và checked"),
        C(92, "ORD-03", "Buy now optional select", "Buy now chọn tùy chọn",
            "Toggle buy_now checkboxes", "Bật/tắt checkbox buy_now",
            "Summary total updates to selected only", "Tổng cập nhật theo invoice được chọn"),
        C(93, "ORD-04", "Shipping validation", "Validation shipping",
            "Submit without required shipping fields", "Submit thiếu field shipping",
            "Server validation errors", "Lỗi validation server"),
        C(94, "ORD-05", "COD complete", "Hoàn tất COD",
            "Select invoices + COD", "Chọn invoice + COD",
            "Selected orders → paid; seller settlement fields set", "Order chọn → paid; set seller settlement"),
        C(95, "ORD-06", "PayPal checkout redirect", "Redirect checkout PayPal",
            "Select + PayPal → approve sandbox", "Chọn + PayPal → approve sandbox",
            "Capture → Confirmation; orders paid", "Capture → Confirmation; order paid"),
        C(96, "ORD-07", "PayPal cancel", "Hủy PayPal",
            "Cancel on PayPal", "Hủy trên PayPal",
            "Return to /Order; orders stay pending_payment", "Về /Order; order vẫn pending_payment"),
        C(97, "ORD-08", "Expired auction win", "Auction win hết hạn",
            "No payment within 48h", "Không thanh toán trong 48h",
            "Order cancelled; triggers winner non-payment policy", "Order cancelled; kích hoạt chính sách không thanh toán"),
        C(98, "ORD-09", "Paid → auction completed", "Paid → auction completed",
            "Pay auction_win order", "Thanh toán order auction_win",
            "Auction status → completed", "Auction status → completed"),
        C(99, "ORD-10", "Header badge count", "Badge header",
            "User with pending orders", "User có order pending",
            "Badge = DB pending count", "Badge = số pending trong DB"),

        C(100, "PAY-01", "Amount mismatch pre-capture", "Sai số tiền trước capture",
            "Tampered amount before capture", "Sửa amount trước capture",
            "Rejected; no payment recorded", "Từ chối; không ghi payment"),
        C(101, "PAY-02", "Post-capture amount diff", "Sai amount sau capture",
            "PayPal returns different amount", "PayPal trả amount khác",
            "Refund triggered; order not wrongly paid", "Kích hoạt refund; order không paid sai"),
        C(102, "PAY-03", "Cancelled order capture", "Capture order đã hủy",
            "Capture on cancelled order", "Capture trên order cancelled",
            "Rejected", "Từ chối"),
        C(103, "PAY-04", "Double return URL", "Double return URL",
            "Hit PayPalReturn twice", "Gọi PayPalReturn hai lần",
            "Idempotent — single payment", "Idempotent — chỉ một payment"),
        C(104, "PAY-05", "Sandbox wallet insufficient", "Ví sandbox không đủ",
            "Sandbox buyer low balance", "Buyer sandbox số dư thấp",
            "Rejected with balance message", "Từ chối kèm thông báo số dư"),
        C(105, "PAY-06", "Deposit capture happy path", "Capture deposit thành công",
            "Registration deposit PayPal flow", "Flow deposit đăng ký PayPal",
            "Deposit paid; registration approved", "Deposit paid; đăng ký approved"),
        C(106, "PAY-07", "Deposit non-pending capture", "Capture deposit không pending",
            "Capture deposit already paid/cancelled", "Capture deposit đã paid/cancelled",
            "Rejected", "Từ chối"),
        C(107, "PAY-08", "Confirmation page", "Trang confirmation",
            "/Payment/Confirmation?orderId=", "/Payment/Confirmation?orderId=",
            "Shows paid order from DB", "Hiển thị order paid từ DB"),

        C(108, "WNP-01", "Winner timeout", "Winner quá hạn",
            "Winner does not pay 48h; ≥2 bidders", "Winner không trả 48h; ≥2 bidder",
            "Order cancelled; deposit forfeited; second-chance order for runner-up", "Order cancelled; mất cọc; order second-chance cho á quân"),
        C(109, "WNP-02", "No runner-up", "Không có á quân",
            "Winner timeout; single bidder", "Winner quá hạn; một bidder",
            "Auction ended; winner cleared; seller relist notification", "Auction ended; xóa winner; thông báo seller relist"),
        C(110, "WNP-03", "Deposit covers order", "Cọc đủ trả order",
            "Winner deposit >= order total at finalize", "Cọc winner >= tổng order khi finalize",
            "Order auto-paid; excess refunded", "Order auto-paid; hoàn phần dư"),
        C(111, "WNP-04", "Anti-snipe skip finalize", "Anti-snipe bỏ finalize",
            "Auction extended by anti-snipe at end", "Auction gia hạn anti-snipe cuối giờ",
            "Finalize skipped until actual expiry", "Bỏ finalize đến khi thực sự hết hạn"),
        C(112, "WNP-05", "Admin audit log", "Log audit admin",
            "Admin Auction Details after recovery", "Admin Auction Details sau recovery",
            "Forfeited deposits + recovery log visible", "Hiển thị cọc bị tịch thu + log recovery"),

        C(113, "FEE-01", "Registration deposit percent", "Phần trăm cọc đăng ký",
            "Register on $500 starting auction", "Đăng ký auction starting $500",
            "Deposit matches PlatformFee config", "Deposit khớp config PlatformFee"),
        C(114, "FEE-02", "Buyer checkout fee", "Phí checkout buyer",
            "Pay won order", "Thanh toán order thắng",
            "platform_fee on order per BuyerCheckoutFeePercent", "platform_fee theo BuyerCheckoutFeePercent"),
        C(115, "FEE-03", "Seller success fee", "Phí thành công seller",
            "Order paid (COD or PayPal)", "Order paid (COD hoặc PayPal)",
            "seller_fee + seller_proceeds calculated correctly", "seller_fee + seller_proceeds tính đúng"),
        C(116, "FEE-04", "Listing fee on approve", "Phí listing khi duyệt",
            "Admin approves seller listing (if enabled)", "Admin duyệt listing seller (nếu bật)",
            "listing_fees row when feature enabled", "Có listing_fees khi feature bật"),
        C(117, "FEE-05", "Deposits excluded from GMV", "Cọc không tính GMV",
            "Dashboard GMV", "GMV dashboard",
            "Registration deposits not counted in GMV", "Cọc đăng ký không tính vào GMV"),

        C(118, "DOC-01", "Public download live", "Download public auction live",
            "Anonymous GET /ProductDocument/Download/{id} live auction", "Anonymous GET /ProductDocument/Download/{id} auction live",
            "PDF download/stream OK", "Download/stream PDF OK"),
        C(119, "DOC-02", "Confirming denied public", "Confirming chặn download public",
            "Download doc on confirming listing", "Download doc listing confirming",
            "403 for anonymous", "403 với anonymous"),
        C(120, "DOC-03", "Admin download confirming", "Admin download confirming",
            "Admin cookie download confirming doc", "Admin cookie download doc confirming",
            "Allowed", "Cho phép"),
        C(121, "DOC-04", "Deleted document", "Document đã xóa",
            "Download soft-deleted doc", "Download doc soft-deleted",
            "404", "404"),
        C(122, "DOC-05", "Certificates tab UI", "Tab Certificates UI",
            "Detail page with documents", "Trang detail có documents",
            "Tab visible; View + Download links", "Tab hiện; link View + Download"),
        C(123, "DOC-06", "Max 5 documents", "Tối đa 5 documents",
            "Upload 6th document seller/admin", "Upload document thứ 6 seller/admin",
            "Validation error", "Lỗi validation"),

        C(124, "CONF-01", "Home excludes confirming", "Home loại confirming",
            "Seeded confirming listing", "Listing confirming đã seed",
            "Not on homepage auction sections", "Không ở mục auction trang chủ"),
        C(125, "CONF-02", "Detail 404 for guest", "Guest detail 404",
            "Guest opens confirming detail", "Guest mở detail confirming",
            "404 or hidden", "404 hoặc ẩn"),
        C(126, "CONF-03", "Register blocked", "Chặn đăng ký",
            "Register on confirming", "Đăng ký trên confirming",
            "Blocked", "Bị chặn"),
        C(127, "CONF-04", "Watchlist blocked", "Chặn watchlist",
            "Add others confirming to watchlist", "Thêm confirming của người khác vào watchlist",
            "Blocked", "Bị chặn"),
        C(128, "CONF-05", "Admin pending count", "Đếm pending admin",
            "Dashboard pending verification", "Dashboard pending verification",
            "Counts confirming only", "Chỉ đếm confirming"),
        C(129, "CONF-06", "Owner can view", "Owner xem được",
            "Seller views own confirming", "Seller xem confirming của mình",
            "Allowed", "Cho phép"),

        C(130, "WATCH-01", "Add live auction", "Thêm auction live",
            "Logged-in user adds live auction", "User login thêm auction live",
            "Watchlist entry created", "Tạo entry watchlist"),
        C(131, "WATCH-02", "Remove from watchlist", "Xóa khỏi watchlist",
            "Toggle off", "Tắt toggle",
            "Entry removed", "Xóa entry"),
        C(132, "WATCH-03", "Watchlist page", "Trang watchlist",
            "/Watchlist", "/Watchlist",
            "Lists user watched live auctions", "Liệt kê auction live user theo dõi"),

        C(133, "NOTIF-01", "Unread badge", "Badge chưa đọc",
            "User receives notification", "User nhận notification",
            "Header badge increments", "Badge header tăng"),
        C(134, "NOTIF-02", "Mark all read", "Đánh dấu đọc hết",
            "Click mark all read", "Bấm mark all read",
            "Badge clears; notifications marked read", "Xóa badge; notification marked read"),
        C(135, "NOTIF-03", "Verification notify", "Thông báo verification",
            "Admin approves/rejects listing", "Admin approve/reject listing",
            "Seller receives in-app notification", "Seller nhận notification in-app"),

        C(136, "FRAUD-01", "User rate limit 429", "Rate limit user 429",
            "Exceed MaxBidsPerMinutePerUser", "Vượt MaxBidsPerMinutePerUser",
            "HTTP 429; no bid insert", "HTTP 429; không insert bid"),
        C(137, "FRAUD-02", "Challenge required", "Yêu cầu challenge",
            "Exceed ChallengeAfterBidsPerMinute without token", "Vượt ChallengeAfterBidsPerMinute không token",
            "403 requiresChallenge", "403 requiresChallenge"),
        C(138, "FRAUD-03", "Stub challenge token", "Token challenge stub",
            "Resubmit with X-Bid-Challenge-Token stub-ok", "Gửi lại với X-Bid-Challenge-Token stub-ok",
            "Bid allowed", "Cho phép bid"),
        C(139, "FRAUD-04", "Rate limit disabled", "Tắt rate limit",
            "BidFraudDetection RateLimitingEnabled=false", "BidFraudDetection RateLimitingEnabled=false",
            "Bids always allowed", "Luôn cho phép bid"),

        C(140, "PAGE-01", "Contact page layout", "Layout trang Contact",
            "/Contact", "/Contact",
            "Hero, info cards, form, map section, footer render", "Hero, card info, form, map, footer render"),
        C(141, "PAGE-02", "Contact form submit", "Submit form Contact",
            "Valid contact form POST", "POST form Contact hợp lệ",
            "Success message or email sent per implementation", "Thông báo thành công hoặc gửi email theo implement"),
        C(142, "PAGE-03", "Contact responsive", "Contact responsive",
            "Mobile viewport 375px", "Viewport mobile 375px",
            "Single column; no horizontal scroll", "Một cột; không scroll ngang"),
        C(143, "PAGE-04", "About / FAQ / Policy", "About / FAQ / Policy",
            "/AboutUs, /Faq, /Policy", "/AboutUs, /Faq, /Policy",
            "Pages load without error", "Trang load không lỗi"),
        C(144, "PAGE-05", "Language switch", "Chuyển ngôn ngữ",
            "/Language/SetCulture", "/Language/SetCulture",
            "UI culture changes if enabled", "UI culture đổi nếu bật"),

        C(145, "AUTO-01", "Full unit/integration suite", "Toàn bộ unit/integration",
            "dotnet test OnlineAuction.Tests", "dotnet test OnlineAuction.Tests",
            "All tests pass (70/70)", "Tất cả test pass (70/70)"),
        C(146, "AUTO-02", "Admin form sync tests", "Test sync form Admin",
            "dotnet test --filter AdminAuctionFormSyncTests", "dotnet test --filter AdminAuctionFormSyncTests",
            "8/8 pass", "8/8 pass"),
        C(147, "AUTO-03", "Release smoke script", "Script smoke release",
            ".\\scripts\\smoke\\Invoke-ReleaseSmoke.ps1", ".\\scripts\\smoke\\Invoke-ReleaseSmoke.ps1",
            "4/4 smoke cases pass or gate documented", "4/4 smoke pass hoặc gate được ghi nhận"),
    ];
}
