// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OnlineAuction.Data;

#nullable disable

namespace OnlineAuction.Migrations
{
    [DbContext(typeof(AuctionHouseDbContext))]
    [Migration("20260701083000_AddIsSuperAdminToUsers")]
    partial class AddIsSuperAdminToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
